### ISSUE TITLE
Ocean spectrum math

### ISSUE THREAD

**Issue by TheCelticGuy** [gasgiant/FFT-Ocean#1]
Hello

Could you please refer me to sources on your ocean spectrum equations? I am not familiar with half of whats going on for your InitSpectrum shaders. 

I am very familiar with Tessendorf's initial spectrum math but you don't seem to be using that one. You seem to be using multiple functions i am unfamiliar with and there is a lot of magic numbers with no explanations for them also.

**Comment by gasgiant** [comment]
Hi

These are my two primary sourses on spectrums math:
1. Christopher J. Horvath. 2015. Empirical directional wave spectra for computer graphics. In Proceedings of the 2015 Symposium on Digital Production (DigiPro '15). Association for Computing Machinery, New York, NY, USA, 29–39. DOI:10.1145/2791261.2791267
2. Gamper T. 2018. Ocean Surface Generation and Rendering, Vienna University of Technology, the Faculty of Informatics.
https://www.cg.tuwien.ac.at/research/publications/2018/GAMPER-2018-OSG/GAMPER-2018-OSG-thesis.pdf

I use TMA energy spectrum. For directional spread I intent to use Hasselman's, but it's a bit wrong in the code currently (works absolutely fine though). I also use Horvath's "swell factor" and mix between this directional spread and a uniform one. All this namedropping will make sence after you read the papers! 

The plethora of magic numbers comes from the fact that these are empirical spectra. This means oceanographers fitted parameters to the data they collected. The exception is NormalisationFactor function, which is simply a polynomial approximation of Q(s) (in Horwath's terms). Hard to calculate Gamma function in compute shader!

**Comment by gasgiant** [comment]
To get the Horwath paper you can ask for the pdf on researchgate. Or you know....https://sci-hub.se/

**Comment by TheCelticGuy** [comment]
Thanks :)
