### ISSUE TITLE
Random guassian numbers for spectra

### ISSUE THREAD

**Issue by TheCelticGuy** [gasgiant/FFT-Ocean#2]
Hi

Me again, I've slowly been learning the math for this as I want to understand it before I use it. 

I read tessendorf's paper but wanted to ask something about the complex number generation for the Fourier amplitudes.

For h0 it is defined as : 1/sqrt(2) * (a + ib) * sqrt(Phillips(kVector));

And h0* (the conjugate) is: 1/sqrt(2) * (a - ib) * sqrt(Phillips(kVector));

Does the conjugate h0* use the same a and b values as the h0 term (but b is negative) or do you generate a second complex number entirely?

**Comment by gasgiant** [comment]
Hi! The conjugate must use the same random numbers.

**Comment by TheCelticGuy** [comment]
Thanks ! I'm sure i'll have more questions in the future but i am slowly understanding it :)
