### ISSUE TITLE
URP Support

### ISSUE THREAD

**Issue by alexandre-root** [gasgiant/FFT-Ocean#4]
Hi!
I was wondering if you planned to convert the "Ocean" shader to URP 🙏
Or you can help me to do so?

Best,

**Comment by gasgiant** [comment]
Hello!

The code as it is in the repository right now is not very good. The simulation part is a lot slower than it needs to be, and the shader is hard to make look good, not to mention that it was tested on my machine exclusively. So using the system as is for a game is a bad idea. I'm in the process of a complete rewrite and will be done probably this month, but it's still for built-in. I have plans to make a URP version, but I imagine it's gonna be quite a bit of work, so no promises on the schedule.

**Comment by alexandre-root** [comment]
Nice to hear it! 😄
