### ISSUE TITLE
How do you compute normal from derivatives

### ISSUE THREAD

**Issue by LthRoseNGun** [gasgiant/FFT-Ocean#6]
Really nice work. I have been working on FFT ocean waves in UE4 for a couple of weeks. I really appreciate you since I referred to your repository heavily. But now I am struggling with normals when putting cascaded waves together. I don't understand why it works. How do you compute normal from derivatives? 

```
float4 derivatives = tex2D(_Derivatives_c0, IN.worldUV / LengthScale0);
#if defined(MID) || defined(CLOSE)
derivatives += tex2D(_Derivatives_c1, IN.worldUV / LengthScale1) * IN.lodScales.y;
#endif

#if defined(CLOSE)
derivatives += tex2D(_Derivatives_c2, IN.worldUV / LengthScale2) * IN.lodScales.z;
#endif

float2 slope = float2(derivatives.x / (1 + derivatives.z),
    derivatives.y / (1 + derivatives.w));
float3 worldNormal = normalize(float3(-slope.x, 1, -slope.y));

o.Normal = WorldToTangentNormalVector(IN, worldNormal);
```

**Comment by gasgiant** [comment]
Check out chapter 4.3 here https://www.cg.tuwien.ac.at/research/publications/2018/GAMPER-2018-OSG/GAMPER-2018-OSG-thesis.pdf  The author lists all the relevant equations there (though he omits proofs for some of them). To prove them you'll need a little bit of triginometry and calculus. Nothing too difficult if you are familiar with those. If not - don't worry, they do indeed work.

**Comment by gasgiant** [comment]
And for cascades - derivatives are linear. You can add together derivatives from cascades just like you do with displacements. Then you calculate the normal. Normals on the other hand are not additive, so it is very convinient that the simulation can output derivatives.

**Comment by LthRoseNGun** [comment]
It helps a lot. Thank you very much.

I have another little problem. The Initial Spectrum h0(k) is quite small. I have to multiply the results by 1e07 to make waves move. 

Since you computed normal like this：

```
slope = <d.x / (1 + d.z), d.y / (1 + d.w)>
```

It will change as the derivatives are scaled. Is that correct?

**Comment by gasgiant** [comment]
The derivatives in question are dimentionless, so the scale shouldn't matter if you do it right. Btw, if I recall correctly h0(k) is suposed to be small. Your waves are so small likely due to Unreal using centimeters insdead of meter as its standard unit (ugh...). The simulation expects length scales in meters and outputs the displacements in meters as well.

**Comment by LthRoseNGun** [comment]
Thanks, bro. I will try to make unreal unit to 1 meter and see.
