### ISSUE TITLE
Method to replace JONSWAP spectrum?

### ISSUE THREAD

**Issue by unaschneck** [gasgiant/FFT-Ocean#8]
Thank you, this is a great model! Really beautiful result! I would be interested in changing the JONSWAP spectrum with a custom wave  spectrum, is there a way to isolate the contributions from JONSWAP? I notice it being explicitly called in WaveSettings, but I want to be sure I have also edited all of the other dependencies that assume a specific spectrum

**Comment by gasgiant** [comment]
You have to change InitialSpectrum.compute. I think this is the only part affected (besides, as you mentioned, WaveSettings or other things that pass the parameters down to the shader).

**Comment by unaschneck** [comment]
Great, thanks I'll give it a look. Thank you for the quick response!
